from pydantic import BaseModel, Field


class AutocompleteRequest(BaseModel):
    """POST rather than GET, and not for REST-purist reasons.

    A GET would put the search text in the request line, which Render's
    access log records and retains. For a logistics app the thing being typed
    is usually somebody's home or workplace, so keeping it in a body rather
    than a URL costs nothing and avoids writing customer addresses into log
    aggregation. Same reasoning applies to the coordinates in
    ReverseGeocodeRequest.
    """

    query: str = Field(min_length=3, max_length=200)

    # Generated by the client, one per search, discarded once the user picks.
    # Passed straight through to Google, where it bundles the whole search
    # into a single billable session.
    session_token: str = Field(min_length=1, max_length=100)


class PlaceSuggestionResponse(BaseModel):
    place_id: str
    description: str
    main_text: str
    secondary_text: str


class AutocompleteResponse(BaseModel):
    suggestions: list[PlaceSuggestionResponse]


class PlaceDetailsRequest(BaseModel):
    place_id: str = Field(min_length=1, max_length=255)

    # Optional: present when this closes an autocomplete session, absent when
    # re-resolving a place id we already hold. That distinction decides
    # whether the coordinate cache may be used — see the router.
    session_token: str | None = Field(default=None, max_length=100)


class ReverseGeocodeRequest(BaseModel):
    lat: float = Field(ge=-90, le=90)
    lng: float = Field(ge=-180, le=180)


class ResolvedPlaceResponse(BaseModel):
    place_id: str
    lat: float
    lng: float

    # EMPTY on a cache hit, and that is not an oversight. The Maps Platform
    # terms let us keep a place id indefinitely and coordinates for 30 days,
    # but not the address — so a cached answer physically cannot include one.
    # Callers that hit the cache are expected to already hold the address:
    # during a search it is the autocomplete suggestion text on screen, and
    # when re-resolving a saved place it is the address stored on the
    # booking. Check `from_cache` before relying on this field.
    address: str

    # Whether the coordinates came from our cache instead of a fresh Google
    # call. Also makes the step D billing check legible: a cache hit must not
    # show up in the Places billing report.
    from_cache: bool = False
