"""add firebase_uid to drivers

Revision ID: 54ac3ec1b83e
Revises: 70b5d919a083
Create Date: 2026-09-02 14:13:32.888826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ac3ec1b83e'
down_revision: Union[str, Sequence[str], None] = '70b5d919a083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('firebase_uid', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_drivers_firebase_uid'), 'drivers', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_firebase_uid'), table_name='drivers')
    op.drop_column('drivers', 'firebase_uid')
    # ### end Alembic commands ###
