"""route distance cache and booking distance source

Revision ID: 5540f1e861e9
Revises: 748441422263
Create Date: 2026-09-04 13:37:18.509757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5540f1e861e9'
down_revision: Union[str, Sequence[str], None] = '748441422263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_distances',
    sa.Column('origin_key', sa.String(length=32), nullable=False),
    sa.Column('dest_key', sa.String(length=32), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('origin_key', 'dest_key')
    )
    op.create_index(op.f('ix_route_distances_created_at'), 'route_distances', ['created_at'], unique=False)
    # ### end Alembic commands ###

    # Not autogenerated correctly: op.add_column with sa.Enum does NOT emit
    # CREATE TYPE on PostgreSQL, so the autogenerated version failed with
    # 'type "distance_source" does not exist'. The type has to be created
    # explicitly, and the column then told not to create it again.
    #
    # Only a real upgrade catches this — the migration file looks right.
    distance_source = sa.Enum('google', 'haversine', name='distance_source')
    distance_source.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'bookings',
        sa.Column(
            'distance_source',
            postgresql.ENUM(
                'google', 'haversine', name='distance_source', create_type=False
            ),
            # Every row predating spec 014 was priced by haversine, so this
            # default labels history honestly rather than optimistically.
            server_default='haversine',
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'distance_source')
    op.drop_index(op.f('ix_route_distances_created_at'), table_name='route_distances')
    op.drop_table('route_distances')
    # ### end Alembic commands ###
    # Not autogenerated: op.add_column with sa.Enum implicitly CREATEs the
    # type, but dropping the column does not drop the type. Without this a
    # downgrade followed by an upgrade fails with "type distance_source
    # already exists".
    sa.Enum(name='distance_source').drop(op.get_bind(), checkfirst=True)
