"""place coordinate cache

Revision ID: 748441422263
Revises: de5f3bd91be4
Create Date: 2026-09-03 13:19:06.015348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748441422263'
down_revision: Union[str, Sequence[str], None] = 'de5f3bd91be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_coordinates',
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_index(op.f('ix_place_coordinates_cached_at'), 'place_coordinates', ['cached_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_coordinates_cached_at'), table_name='place_coordinates')
    op.drop_table('place_coordinates')
    # ### end Alembic commands ###
