"""one active booking per driver

Revision ID: 8b643da8c609
Revises: 54ac3ec1b83e
Create Date: 2026-09-02 14:30:02.415766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b643da8c609'
down_revision: Union[str, Sequence[str], None] = '54ac3ec1b83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('one_active_booking_per_driver', 'bookings', ['driver_id'], unique=True, postgresql_where=sa.text("status IN ('driver_assigned', 'picked_up')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('one_active_booking_per_driver', table_name='bookings', postgresql_where=sa.text("status IN ('driver_assigned', 'picked_up')"))
    # ### end Alembic commands ###
