"""add distance source to bookings

Revision ID: afbcf9152650
Revises: 748441422263
Create Date: 2026-09-05 04:21:54.823717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'afbcf9152650'
down_revision: Union[str, Sequence[str], None] = '748441422263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### end Alembic commands ###
    # Autogenerate gets this wrong: op.add_column with sa.Enum does NOT emit
    # CREATE TYPE on PostgreSQL, so the generated version fails with
    # 'type "distance_source" does not exist'. The type has to be created
    # explicitly and the column then told not to create it again.
    #
    # The migration file looks correct either way — only running it finds out,
    # which is why every migration here is round-tripped before committing.
    distance_source = sa.Enum('google', 'haversine', name='distance_source')
    distance_source.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'bookings',
        sa.Column(
            'distance_source',
            postgresql.ENUM(
                'google', 'haversine', name='distance_source', create_type=False
            ),
            # Every row predating spec 014 was priced by haversine, so this
            # labels history honestly rather than optimistically.
            server_default='haversine',
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### end Alembic commands ###
    op.drop_column('bookings', 'distance_source')
    # Also not autogenerated: dropping the column does not drop the type, so
    # without this a downgrade followed by an upgrade fails with
    # 'type "distance_source" already exists'.
    sa.Enum(name='distance_source').drop(op.get_bind(), checkfirst=True)
