"""create users, drivers, vehicle_types, bookings

Revision ID: cf05ce9850a0
Revises: 
Create Date: 2026-08-07 13:53:36.999119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf05ce9850a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('vehicle_types',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('base_fare_paise', sa.Integer(), nullable=False),
    sa.Column('included_km', sa.Numeric(precision=4, scale=1, asdecimal=False), nullable=False),
    sa.Column('per_km_paise', sa.Integer(), nullable=False),
    sa.Column('min_fare_paise', sa.Integer(), nullable=False),
    sa.Column('capacity_kg', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type_code', sa.String(length=20), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1, asdecimal=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_type_code'], ['vehicle_types.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_phone'), 'drivers', ['phone'], unique=True)
    op.create_index(op.f('ix_drivers_vehicle_type_code'), 'drivers', ['vehicle_type_code'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_code', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'driver_assigned', 'picked_up', 'delivered', 'cancelled', 'expired', name='booking_status'), nullable=False),
    sa.Column('pickup_address', sa.String(length=255), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lng', sa.Float(), nullable=False),
    sa.Column('drop_address', sa.String(length=255), nullable=False),
    sa.Column('drop_lat', sa.Float(), nullable=False),
    sa.Column('drop_lng', sa.Float(), nullable=False),
    sa.Column('goods_description', sa.String(length=255), nullable=False),
    sa.Column('approx_weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('quoted_fare_paise', sa.Integer(), nullable=False),
    sa.Column('quoted_distance_m', sa.Integer(), nullable=False),
    sa.Column('quoted_eta_minutes', sa.Integer(), nullable=False),
    sa.Column('quoted_base_fare_paise', sa.Integer(), nullable=False),
    sa.Column('quoted_included_km', sa.Numeric(precision=4, scale=1, asdecimal=False), nullable=False),
    sa.Column('quoted_per_km_paise', sa.Integer(), nullable=False),
    sa.Column('quoted_min_fare_paise', sa.Integer(), nullable=False),
    sa.Column('final_fare_paise', sa.Integer(), nullable=True),
    sa.Column('final_distance_m', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('cash', 'online', name='payment_method'), nullable=False),
    sa.Column('driver_assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Enum('customer', 'driver', 'system', name='cancelled_by'), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_code'], ['vehicle_types.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_driver_id'), 'bookings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_bookings_public_code'), 'bookings', ['public_code'], unique=True)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_public_code'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_driver_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_table('bookings')
    sa.Enum(name='cancelled_by').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='payment_method').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='booking_status').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_drivers_vehicle_type_code'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_phone'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_table('vehicle_types')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
