"""index for pending booking expiry sweep

Revision ID: d506e0ada20f
Revises: 8b643da8c609
Create Date: 2026-09-03 01:54:27.562160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd506e0ada20f'
down_revision: Union[str, Sequence[str], None] = '8b643da8c609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Plain CREATE INDEX, not CONCURRENTLY. It takes an ACCESS EXCLUSIVE lock
    and blocks writes to bookings for its duration - milliseconds on a table
    this size. If bookings ever grows enough for that pause to matter, switch
    to postgresql_concurrently=True inside an
    op.get_context().autocommit_block(), since CONCURRENTLY cannot run inside
    a transaction.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bookings_pending_created_at', 'bookings', ['created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_pending_created_at', table_name='bookings', postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###
