"""add place ids to bookings

Revision ID: de5f3bd91be4
Revises: d506e0ada20f
Create Date: 2026-09-03 13:02:58.748725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5f3bd91be4'
down_revision: Union[str, Sequence[str], None] = 'd506e0ada20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pickup_place_id', sa.String(length=255), nullable=True))
    op.add_column('bookings', sa.Column('drop_place_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'drop_place_id')
    op.drop_column('bookings', 'pickup_place_id')
    # ### end Alembic commands ###
